import initTabNav from './modules/tabnav.js';
import initAccordionList from './modules/accordion-list.js';
import initScrollSuave from './modules/scroll-suave.js';
import initAnimaScroll from './modules/anima-scroll.js';
import initModal from './modules/modal.js';
import initTooltip from './modules/tooltip.js';
import initDropdownMenu from './modules/dropdown-menu.js';
import initOutsideClick from './modules/outsideclick.js';
import initMenuMobile from './modules/menu-mobile.js';
import initAnimaNumeros from './modules/anima-numeros.js';
import initFuncionamento from './modules/funcionamento.js';

initTabNav();
initAccordionList();
initScrollSuave();
initAnimaScroll();
initModal();
initTooltip();
initDropdownMenu();
initOutsideClick();
initMenuMobile();
initAnimaNumeros();
initFuncionamento();